### ISSUE TITLE
new version is not working for me

### ISSUE THREAD

**Issue by raykai** [ppfeufer/eve-online-killboard-widget#57]
the new version is not working for me... it just says Loading killboard data, please wait ...
then the widget is blank just has the name of the widget. it was working before ... was slow fetching the info tho.

**Comment by ppfeufer** [comment]
First, make sure it is really the latest version, I had to do a quick hotfix, so v0.26.6 is what you're looking for.

If that's the version you have, I need a little input from you.
Go to your Widget Settings and uncheck the "FC, I am using a static cache, halp!!" checkbox. That forces the Widget to load directly instead of dynamically in the background. With a bit of luck, you already get an error message after that in your frontend. 

If not, then you need to edit your wp-config.php file and activate the debug mode. You do so by writing ``define('WP_DEBUG', true);`` in there. Best right after your Database settings. Save the file and reload your Frontend. That should definitely give you an error message.

Also please let me know which WordPress version and PHP version you are running.
You need at least WordPress 5.0 and PHP 7.2 for this.

**Comment by ppfeufer** [comment]
Ah, nevermind, I think I just found out what the issue is here ..
Give me a moment, another hotfix incoming as soon as I am back home.

**Comment by raykai** [comment]
when i activate the plugin i get an error
`Fatal error: Uncaught TypeError: Argument 1 passed to WordPress\EsiClient\Swagger::getResponseArray() must be of the type array, string given, called in /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/EsiClient/Swagger.php on line 240 and defined in /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/EsiClient/Swagger.php:249 Stack trace: #0 /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/EsiClient/Swagger.php(240): WordPress\EsiClient\Swagger->getResponseArray('{"corporations"...') #1 /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/EsiClient/Repository/UniverseRepository.php(186): WordPress\EsiClient\Swagger->callEsi() #2 /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/themes/eve-online/Helper/EsiHelper.php(155): WordPress\EsiClient\Repository\UniverseRepository->universeIds(Array) #3 /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/themes/eve-online/Helper/EsiHelper in /var/www/vhosts/kratshost.com/legionofthedrakkars.kratshost.com/wp-content/EsiClient/Swagger.php on line 249`

if i refresh the page i get: `The plugin generated 853 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.`

in the wiget window i get : `WordPress database error: [Table 'legionofthedrakkars_wp.wpx_eve_online_killboard_widget_cache' doesn't exist]
SELECT * FROM wpx_eve_online_killboard_widget_cache WHERE cache_key = 'EVE Online :: ID corporation/Legion of the Drakkars' AND valid_until > '1560278438'`

**Comment by ppfeufer** [comment]
Update the theme btw » https://github.com/ppfeufer/eve-online-wordpress-theme/releases

**Comment by ppfeufer** [comment]
But ya, the issue here is, I forgot to clear the cache table, so the widget gets old cached data which it can't handle no longer, because of the new ESI client structure. The theme itself in the older version still can handle these, but it's currently just reading it from the cache table.

So as soon as I get the hotfix out, you need to update the widget **and** the theme. Both are depending on the ESI client the update brings with it.

For now, just leave the widget inactive and hope that your cache is not about to expire.

**Comment by raykai** [comment]
il update the theme now :)

**Comment by ppfeufer** [comment]
No, not yet please, **after** I got the hotfix for the widget out

**Comment by raykai** [comment]
ok

**Comment by ppfeufer** [comment]
So, now please update to the new releases

- Widget » https://github.com/ppfeufer/eve-online-killboard-widget/releases/tag/v0.26.7
- Theme » https://github.com/ppfeufer/eve-online-wordpress-theme/releases/tag/v0.1-r20190611.2

This should take care of your issue.

**Comment by raykai** [comment]
when activating the Widget i get the error: The plugin generated 1082 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

and im getting errors on widget: 
![bug](https://user-images.githubusercontent.com/8138894/59351395-53f13d00-8cec-11e9-9e93-aa62ee6a3691.PNG)

**Comment by ppfeufer** [comment]
That error means that, at some point, during this update (if it was my fault, sorry for the inconvenience) your killboard cache table got lost,.

Open your phpMyAdmin, go to your WordPress database and execute the following command:
```mysql
CREATE TABLE wpx_eve_online_killboard_widget_cache(
    cache_key varchar(255),
    value longtext,
    valid_until varchar(255),
    PRIMARY KEY cache_key (cache_key)
)
```

**Comment by raykai** [comment]
ok, phpMyAdmin gave me this: MySQL returned an empty result set (i.e. zero rows). (Query took 0.0587 seconds.) CREATE TABLE wpx_eve_online_killboard_widget_cache( cache_key varchar(255), value longtext, valid_until varchar(255), PRIMARY KEY cache_key (cache_key) )

but now the widget is giving me the error: WordPress database error: [Table 'legionofthedrakkars_wp.wpx_eve_online_esi_cache' doesn't exist]
SELECT * FROM wpx_eve_online_esi_cache WHERE esi_route = 'universe/systems/31001807' AND valid_until > '1560346418'

Having some Table probs :(

**Comment by ppfeufer** [comment]
The empty return is normal on table creation, because there is nothing than can be returned. What you now get, is a different table that can't be found. Which made me look through my code and all, and there is actually no way these 2 tables could have been removed from the DB automatically or by accident by either the theme or the widget. But what ever ... here is what you do now, again in phpMyAdmin in your WP database:

```mysql
CREATE TABLE wpx_eve_online_esi_cache (
    cache_key varchar(255),
    value longtext,
    valid_until varchar(255),
    PRIMARY KEY cache_key (cache_key)
)
```

**Comment by raykai** [comment]
that is strange as i did not play with the DB at all...

**Comment by raykai** [comment]
ok i did the 

```
CREATE TABLE wpx_eve_online_esi_cache (
    cache_key varchar(255),
    value longtext,
    valid_until varchar(255),
    PRIMARY KEY cache_key (cache_key)
)
```
its now saying this : 
WordPress database error: [Unknown column 'esi_route' in 'where clause']
SELECT * FROM wpx_eve_online_esi_cache WHERE esi_route = 'universe/systems/31001807' AND valid_until > '1560347290'

**Comment by raykai** [comment]
![db](https://user-images.githubusercontent.com/8138894/59356856-bb60ba00-8cf7-11e9-8123-8f2859a962e4.PNG)

**Comment by ppfeufer** [comment]
UPs, that was my mistake, copyx-paste error. Happens when I try to solve that while sitting in the office.

remove the ``wpx_eve_online_esi_cache`` TABLE AGAIN AND RECREATE IT WITH.

```mysql
CREATE TABLE wpx_eve_online_esi_cache (
    esi_route varchar(255),
    value longtext,
    valid_until varchar(255),
    PRIMARY KEY cache_key (esi_route)
)
```

**Comment by raykai** [comment]
sweet its working now. thank you for your help :)  and have a good day at work.

**Comment by ppfeufer** [comment]
YAY!!!! We did it reddit :-P

Enjoy the fun now with your website.
